@startuml "Классы"
left to right direction

artifact игрок1
artifact игрок2
node сервер
node игра
node счёт1
node счёт2
node клетки1
node клетки2
node клетки

игрок1 <--> игра
игрок2 <--> игра
игра --> сервер
сервер --> клетки1
сервер --> клетки2
сервер --> счёт1
сервер --> счёт2
сервер --> клетки

@enduml