@startuml
left to right direction
actor клиент
actor банк
rectangle Банкомат{
  клиент--(Проверка баланса)
  клиент--(Снятие наличных)
  клиент--(Положить наличные на карту)
  (Снятие наличных) ->(Проверка баланса) :extends
  (проверить остатки наличных)--банк
}
@enduml