@startuml "Монополия классы"
left to right direction

class игрок{
    Имя: string
    Счёт: varchar
    Клетки: string
    Взять_деньги()
    Отдать_деньги()
    Проверить_счёт()
    Сделать_ход()
    Купить_клетку()
    Отдать_клетку()
    Обмен()
}

class машина{
    ID: string
    Сложность: varchar
    Клетки: string
    Взять_деньги()
    Отдать_деньги()
    Проверить_счёт()
    Сделать_ход()
    Купить_клетку()
    Отдать_клетку()
    Обмен()
}

class игра{
    Клетки: string
    Отдать_деньги()
    Взять_деньги()
    Продать_клетку()
}

игра <-- игрок: действие
игрок <-- игра: ответ на действие
игра <-- машина: действие
машина <-- игра: ответ на действие
игрок <--> машина: обмен

@enduml