@startuml Monopoly
left to right direction
actor игрок
actor машина
rectangle игра {
    игрок -- (взять деньги)
    игрок -- (отдать деньги)
    игрок -- (сделать ход)
    игрок -- (купить клетку)
    игрок -- (отдать клетку)
    игрок -- (проверить счёт)
    игрок -- (обмен)
    (купить клетку) <- (проверить счёт) :include
    (отдать клетку) <- (проверить счёт) :extend
    (отдать деньги) <- (проверить счёт) :extend
    (взять деньги) -- машина
    (отдать деньги) -- машина
    (сделать ход) -- машина
    (купить клетку) -- машина
    (отдать клетку) -- машина
    (проверить счёт) -- машина
    (обмен) -- машина
}
@enduml